version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "⬆ ci"
    labels:
      - dependencies
      - github-actions
    open-pull-requests-limit: 5
    groups:
      actions-minor:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "⬆ deps"
    labels:
      - dependencies
      - javascript
    open-pull-requests-limit: 10
    versioning-strategy: increase
    allow:
      - dependency-name: "*"
        update-types:
          - version-update:semver-patch
    groups:
      npm-patch:
        applies-to: version-updates
        patterns:
          - "*"
        exclude-patterns:
          - next
        update-types:
          - patch

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "⬆ docker"
    labels:
      - dependencies
      - docker
    open-pull-requests-limit: 5
    allow:
      - dependency-name: "*"
        update-types:
          - version-update:semver-minor
          - version-update:semver-patch
