import { config } from "../utils/config";
import * as pgSchema from "./schema-pg";
import * as sqliteSchema from "./schema-sqlite";

const schema = (config.dbType === "sqlite" ? sqliteSchema : pgSchema) as typeof pgSchema;

export const apiKeys = schema.apiKeys;
export const upstreams = schema.upstreams;
export const upstreamHealth = schema.upstreamHealth;
export const upstreamProbeResults = schema.upstreamProbeResults;
export const apiKeyUpstreams = schema.apiKeyUpstreams;
export const circuitBreakerStates = schema.circuitBreakerStates;
export const upstreamFailureRules = schema.upstreamFailureRules;
export const requestLogs = schema.requestLogs;
export const trafficRecordingSettings = schema.trafficRecordingSettings;
export const trafficRecordings = schema.trafficRecordings;
export const compensationRules = schema.compensationRules;
export const billingModelPrices = schema.billingModelPrices;
export const billingManualPriceOverrides = schema.billingManualPriceOverrides;
export const billingTierRules = schema.billingTierRules;
export const billingPriceSyncHistory = schema.billingPriceSyncHistory;
export const backgroundSyncTasks = schema.backgroundSyncTasks;
export const backgroundSyncTaskRuns = schema.backgroundSyncTaskRuns;
export const requestBillingSnapshots = schema.requestBillingSnapshots;
export const cliproxyInstances = schema.cliproxyInstances;

export const apiKeysRelations = schema.apiKeysRelations;
export const upstreamsRelations = schema.upstreamsRelations;
export const upstreamHealthRelations = schema.upstreamHealthRelations;
export const upstreamProbeResultsRelations = schema.upstreamProbeResultsRelations;
export const circuitBreakerStatesRelations = schema.circuitBreakerStatesRelations;
export const upstreamFailureRulesRelations = schema.upstreamFailureRulesRelations;
export const apiKeyUpstreamsRelations = schema.apiKeyUpstreamsRelations;
export const requestLogsRelations = schema.requestLogsRelations;
export const trafficRecordingsRelations = schema.trafficRecordingsRelations;
export const requestBillingSnapshotsRelations = schema.requestBillingSnapshotsRelations;

export type ApiKey = typeof apiKeys.$inferSelect;
export type NewApiKey = typeof apiKeys.$inferInsert;
export type Upstream = typeof upstreams.$inferSelect;
export type NewUpstream = typeof upstreams.$inferInsert;
export type UpstreamHealth = typeof upstreamHealth.$inferSelect;
export type NewUpstreamHealth = typeof upstreamHealth.$inferInsert;
export type UpstreamProbeResult = typeof upstreamProbeResults.$inferSelect;
export type NewUpstreamProbeResult = typeof upstreamProbeResults.$inferInsert;
export type ApiKeyUpstream = typeof apiKeyUpstreams.$inferSelect;
export type NewApiKeyUpstream = typeof apiKeyUpstreams.$inferInsert;
export type RequestLog = typeof requestLogs.$inferSelect;
export type NewRequestLog = typeof requestLogs.$inferInsert;
export type TrafficRecordingSettings = typeof trafficRecordingSettings.$inferSelect;
export type NewTrafficRecordingSettings = typeof trafficRecordingSettings.$inferInsert;
export type TrafficRecording = typeof trafficRecordings.$inferSelect;
export type NewTrafficRecording = typeof trafficRecordings.$inferInsert;
export type CircuitBreakerState = typeof circuitBreakerStates.$inferSelect;
export type NewCircuitBreakerState = typeof circuitBreakerStates.$inferInsert;
export type UpstreamFailureRule = typeof upstreamFailureRules.$inferSelect;
export type NewUpstreamFailureRule = typeof upstreamFailureRules.$inferInsert;
export type BillingModelPrice = typeof billingModelPrices.$inferSelect;
export type NewBillingModelPrice = typeof billingModelPrices.$inferInsert;
export type BillingManualPriceOverride = typeof billingManualPriceOverrides.$inferSelect;
export type NewBillingManualPriceOverride = typeof billingManualPriceOverrides.$inferInsert;
export type BillingTierRule = typeof billingTierRules.$inferSelect;
export type NewBillingTierRule = typeof billingTierRules.$inferInsert;
export type BillingPriceSyncHistory = typeof billingPriceSyncHistory.$inferSelect;
export type NewBillingPriceSyncHistory = typeof billingPriceSyncHistory.$inferInsert;
export type BackgroundSyncTask = typeof backgroundSyncTasks.$inferSelect;
export type NewBackgroundSyncTask = typeof backgroundSyncTasks.$inferInsert;
export type BackgroundSyncTaskRun = typeof backgroundSyncTaskRuns.$inferSelect;
export type NewBackgroundSyncTaskRun = typeof backgroundSyncTaskRuns.$inferInsert;
export type RequestBillingSnapshot = typeof requestBillingSnapshots.$inferSelect;
export type NewRequestBillingSnapshot = typeof requestBillingSnapshots.$inferInsert;
export type CliproxyInstance = typeof cliproxyInstances.$inferSelect;
export type NewCliproxyInstance = typeof cliproxyInstances.$inferInsert;
