name: Feature Request
description: Suggest a new feature or improvement
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea in detail.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Describe the pain point or limitation
      placeholder: When I try to..., I find that...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this problem to be solved?
      placeholder: I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you've considered
      placeholder: I also considered...

  - type: textarea
    id: usecase
    attributes:
      label: Use Case
      description: Describe a specific use case to help us understand the requirement
      placeholder: |
        As a [user role],
        I want [feature],
        so that [goal].

  - type: dropdown
    id: priority
    attributes:
      label: Priority Suggestion
      description: How urgent is this feature for you?
      options:
        - Low - Nice to have
        - Medium - Would significantly improve experience
        - High - Blocking my use case

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I'm willing to submit a PR to implement this feature
